---
service: st_gym

image: pschuez/st_gym

servers:
  web:
    hosts:
      - 168.119.127.165
  # job:
  #   hosts:
  #     - 168.119.127.165
  #   cmd: bin/jobs

registry:
  username: pschuez
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: aarch64

proxy:
  ssl: true
  hosts:
    - gym.margareti.com
    - www.gym.margareti.com

env:
  clear:
    SOLID_QUEUE_IN_PUMA: true
  secret:
    - RAILS_MASTER_KEY

ssh:
  user: root

volumes:
  - "storage:/rails/storage"

asset_path: /rails/public/assets

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
