---
service: st_gym

image: pschuez/st_gym

servers:
  web:
    hosts:
      - 168.119.127.165
  worker:
    hosts:
      - 168.119.127.165
    cmd: bundle exec sidekiq #-C config/sidekiq.yml

registry:
  username: pschuez
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: aarch64

proxy:
  app_port: 3000
  ssl: false
  hosts:
    - gym.margareti.com
    - www.gym.margareti.com

env:
  clear:
    DB_HOST: 168.119.127.165
    POSTGRES_USER: st_gym_user
    POSTGRES_DB: st_gym_production
    redis: 168.119.127.165
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - REDIS_URL

ssh:
  user: root

accessories:
  db:
    image: postgres:16
    host: 168.119.127.165
    port: 5431:5432
    env:
      clear:
        POSTGRES_USER: st_gym_user
        POSTGRES_DB: st_gym_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
  redis:
    image: redis:7.0
    roles:
      - web
      - worker
    port: 6380:6379
    directories:
      - data:/data

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
