---
service: st_gym
image: pschuez/st_gym
servers:
- 49.13.123.144
registry:
  username: pschuez
  password:
  - KAMAL_REGISTRY_PASSWORD
env:
  clear:
    DB_HOST: 49.13.123.144
    POSTGRES_USER: st_gym_user
    POSTGRES_DB: st_gym_production
    REDIS_URL: redis://49.13.123.144:6379/1
    redis: 49.13.123.144
  secret:
  - RAILS_MASTER_KEY
  - POSTGRES_PASSWORD
ssh:
  user: root
accessories:
  db:
    image: postgres:16
    host: 49.13.123.144
    port: 5432
    env:
      clear:
        POSTGRES_USER: st_gym_user
        POSTGRES_DB: st_gym_production
      secret:
      - POSTGRES_PASSWORD
    directories:
    - data:/var/lib/postgresql/data
  redis:
    image: redis:7.0
    host: 49.13.123.144
    port: 6379
    directories:
    - data:/data
