---
service: st_gym
image: pschuez/st_gym
servers:
  web:
    hosts:
      - 168.119.127.165
    options:
      "add-host": host.docker.internal:host-gateway
    labels:
      traefik.http.routers.stgym.entrypoints: websecure
      traefik.http.routers.stgym.rule: "Host(`gym.margareti`) || Host(`www.gym.margareti.com`)"
      traefik.http.routers.stgym.tls.certresolver: letsencrypt
      traefik.http.routers.stgym.tls.domains[0].main: gym.margareti.com
      traefik.http.routers.stgym.tls.domains[0].sans: www.gym.margareti.com
  worker:
    hosts:
      - 168.119.127.165
    cmd: bundle exec sidekiq #-C config/sidekiq.yml
registry:
  username: pschuez
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  clear:
    DB_HOST: 168.119.127.165
    POSTGRES_USER: st_gym_user
    POSTGRES_DB: st_gym_production
    redis: 168.119.127.165
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - REDIS_URL
ssh:
  user: root
accessories:
  db:
    image: postgres:16
    host: 168.119.127.165
    port: 5431:5432
    env:
      clear:
        POSTGRES_USER: st_gym_user
        POSTGRES_DB: st_gym_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
  redis:
    image: redis:7.0
    roles:
      - web
      - worker
    port: 6380:6379
    directories:
      - data:/data

